# Generated by Django 5.0 on 2023-12-17 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Speciality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='Family',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='Gender',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='Name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='Scores',
            field=models.FloatField(default=1, help_text='Please be between 1 and 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='Specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Speciality.speciality'),
        ),
    ]
