# Generated by Django 5.0 on 2023-12-17 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Speciality', '0002_doctor_address_doctor_family_doctor_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='PatientName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Speciality.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='Text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='PhoneNumber',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='Age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='Family',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='Name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='PhoneNumber',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='DateAndTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserve',
            name='Family',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='Name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='Name_Doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Speciality.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='PhoneNumber',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciality',
            name='Name_Specialty',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Gender',
            field=models.BooleanField(help_text=' Light tick for male , Hide tick for female'),
        ),
    ]
