# Generated by Django 4.2 on 2023-12-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Speciality', '0003_comment_patientname_comment_text_doctor_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Text',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='speciality',
            old_name='Name_Specialty',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='PatientName',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Family',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Scores',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Family',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='DateAndTime',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='Family',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='Name_Doctor',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='comment',
            name='Doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Speciality.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='User',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='Count_Scores',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Sum_Scores',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='Bimar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Speciality.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='Doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Speciality.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='Time',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Speciality.speciality'),
            preserve_default=False,
        ),
    ]
